name: Risevest Web App Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false  # Ensure that failure on one browser doesn't affect others
      matrix:
        browser: [chrome, firefox, edge, electron]  # Browsers to test

    env:
      NODE_VERSION: '20'
      CYPRESS_CACHE_FOLDER: ~/.cache/Cypress

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Updated to v4 for compatibility

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}  # Use environment variable

      - name: Cache Node modules
        uses: actions/cache@v4  # Updated to v4 for compatibility
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Cypress binary
        uses: actions/cache@v4  # Updated to v4 for compatibility
        with:
          path: ${{ env.CYPRESS_CACHE_FOLDER }}
          key: ${{ runner.os }}-cypress-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies
        run: npm ci

      - name: Ensure Cypress binary permissions
        run: chmod +x ${{ env.CYPRESS_CACHE_FOLDER }}/13.15.0/Cypress/Cypress

      - name: Install Cypress
        run: sudo npx cypress install

      - name: Create reports directory
        run: |
          mkdir -p cypress/reports/allure-results  # Directory for Allure results
          mkdir -p cypress/reports/mochawesome  # Directory for Mochawesome reports

      - name: Run Cypress tests with Allure on ${{ matrix.browser }}
        run: |
          sudo apt-get install -y xvfb
          xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" npx cypress run --browser ${{ matrix.browser }} --env allureOutputPath=cypress/reports/allure-results || true  # Allow failures without breaking the workflow
          echo "Cypress test run completed."

      - name: Generate Allure Report
        run: |
          npx allure generate cypress/reports/allure-results --clean --output cypress/reports/allure-report  # Generate Allure report
          echo "Allure report generated."

      - name: Check for Allure results
        run: |
          echo "Checking for Allure results files..."
          if [ -d "cypress/reports/allure-results" ]; then
            echo "Allure results directory found."
            if ls cypress/reports/allure-results/*.json 1> /dev/null